// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imabg/authx/internal/mail (interfaces: Mailer)
//
// Generated by this command:
//
//	mockgen -destination=mock/mail_mock.go -package=mock github.com/imabg/authx/internal/mail Mailer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	mail "github.com/imabg/authx/internal/mail"
	gomock "go.uber.org/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendMagicLink mocks base method.
func (m *MockMailer) SendMagicLink(ctx context.Context, cfg mail.Config, to, link string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMagicLink", ctx, cfg, to, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMagicLink indicates an expected call of SendMagicLink.
func (mr *MockMailerMockRecorder) SendMagicLink(ctx, cfg, to, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMagicLink", reflect.TypeOf((*MockMailer)(nil).SendMagicLink), ctx, cfg, to, link)
}

// SendOTP mocks base method.
func (m *MockMailer) SendOTP(ctx context.Context, cfg mail.Config, to, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOTP", ctx, cfg, to, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendOTP indicates an expected call of SendOTP.
func (mr *MockMailerMockRecorder) SendOTP(ctx, cfg, to, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOTP", reflect.TypeOf((*MockMailer)(nil).SendOTP), ctx, cfg, to, code)
}
