// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imabg/authx/internal/app (interfaces: IRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/app_mock.go -package=mock -mock_names=IRepository=MockAppRepository github.com/imabg/authx/internal/app IRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	app "github.com/imabg/authx/internal/app"
	gomock "go.uber.org/mock/gomock"
)

// MockAppRepository is a mock of IRepository interface.
type MockAppRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppRepositoryMockRecorder
	isgomock struct{}
}

// MockAppRepositoryMockRecorder is the mock recorder for MockAppRepository.
type MockAppRepositoryMockRecorder struct {
	mock *MockAppRepository
}

// NewMockAppRepository creates a new mock instance.
func NewMockAppRepository(ctrl *gomock.Controller) *MockAppRepository {
	mock := &MockAppRepository{ctrl: ctrl}
	mock.recorder = &MockAppRepositoryMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppRepository) EXPECT() *MockAppRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppRepository) Create(ctx context.Context, application app.Application) (app.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, application)
	ret0, _ := ret[0].(app.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAppRepositoryMockRecorder) Create(ctx, application any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppRepository)(nil).Create), ctx, application)
}

// ExistsByClientID mocks base method.
func (m *MockAppRepository) ExistsByClientID(ctx context.Context, clientID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByClientID", ctx, clientID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByClientID indicates an expected call of ExistsByClientID.
func (mr *MockAppRepositoryMockRecorder) ExistsByClientID(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByClientID", reflect.TypeOf((*MockAppRepository)(nil).ExistsByClientID), ctx, clientID)
}

// GetByClientID mocks base method.
func (m *MockAppRepository) GetByClientID(ctx context.Context, clientID string) (app.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByClientID", ctx, clientID)
	ret0, _ := ret[0].(app.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByClientID indicates an expected call of GetByClientID.
func (mr *MockAppRepositoryMockRecorder) GetByClientID(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByClientID", reflect.TypeOf((*MockAppRepository)(nil).GetByClientID), ctx, clientID)
}

// GetByID mocks base method.
func (m *MockAppRepository) GetByID(ctx context.Context, id uuid.UUID) (app.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(app.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAppRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAppRepository)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockAppRepository) Update(ctx context.Context, application app.Application) (app.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, application)
	ret0, _ := ret[0].(app.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAppRepositoryMockRecorder) Update(ctx, application any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAppRepository)(nil).Update), ctx, application)
}
