// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imabg/authx/internal/challenge (interfaces: IRepository,IService)
//
// Generated by this command:
//
//	mockgen -destination=mock/challenge_mock.go -package=mock -mock_names=IRepository=MockChallengeRepository,IService=MockChallengeService github.com/imabg/authx/internal/challenge IRepository,IService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	challenge "github.com/imabg/authx/internal/challenge"
	gomock "go.uber.org/mock/gomock"
)

// MockChallengeRepository is a mock of IRepository interface.
type MockChallengeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChallengeRepositoryMockRecorder
	isgomock struct{}
}

// MockChallengeRepositoryMockRecorder is the mock recorder for MockChallengeRepository.
type MockChallengeRepositoryMockRecorder struct {
	mock *MockChallengeRepository
}

// NewMockChallengeRepository creates a new mock instance.
func NewMockChallengeRepository(ctrl *gomock.Controller) *MockChallengeRepository {
	mock := &MockChallengeRepository{ctrl: ctrl}
	mock.recorder = &MockChallengeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallengeRepository) EXPECT() *MockChallengeRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockChallengeRepository) Consume(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockChallengeRepositoryMockRecorder) Consume(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockChallengeRepository)(nil).Consume), ctx, id)
}

// Create mocks base method.
func (m *MockChallengeRepository) Create(ctx context.Context, c challenge.Challenge) (challenge.Challenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(challenge.Challenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockChallengeRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChallengeRepository)(nil).Create), ctx, c)
}

// GetOpenByHash mocks base method.
func (m *MockChallengeRepository) GetOpenByHash(ctx context.Context, applicationID uuid.UUID, challengeType, secretHash string) (challenge.Challenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenByHash", ctx, applicationID, challengeType, secretHash)
	ret0, _ := ret[0].(challenge.Challenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenByHash indicates an expected call of GetOpenByHash.
func (mr *MockChallengeRepositoryMockRecorder) GetOpenByHash(ctx, applicationID, challengeType, secretHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenByHash", reflect.TypeOf((*MockChallengeRepository)(nil).GetOpenByHash), ctx, applicationID, challengeType, secretHash)
}

// GetOpenByTarget mocks base method.
func (m *MockChallengeRepository) GetOpenByTarget(ctx context.Context, applicationID uuid.UUID, target, challengeType string) (challenge.Challenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenByTarget", ctx, applicationID, target, challengeType)
	ret0, _ := ret[0].(challenge.Challenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenByTarget indicates an expected call of GetOpenByTarget.
func (mr *MockChallengeRepositoryMockRecorder) GetOpenByTarget(ctx, applicationID, target, challengeType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenByTarget", reflect.TypeOf((*MockChallengeRepository)(nil).GetOpenByTarget), ctx, applicationID, target, challengeType)
}

// IncrementAttempts mocks base method.
func (m *MockChallengeRepository) IncrementAttempts(ctx context.Context, id uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAttempts", ctx, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementAttempts indicates an expected call of IncrementAttempts.
func (mr *MockChallengeRepositoryMockRecorder) IncrementAttempts(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAttempts", reflect.TypeOf((*MockChallengeRepository)(nil).IncrementAttempts), ctx, id)
}

// InvalidateOpen mocks base method.
func (m *MockChallengeRepository) InvalidateOpen(ctx context.Context, applicationID uuid.UUID, target, challengeType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateOpen", ctx, applicationID, target, challengeType)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateOpen indicates an expected call of InvalidateOpen.
func (mr *MockChallengeRepositoryMockRecorder) InvalidateOpen(ctx, applicationID, target, challengeType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateOpen", reflect.TypeOf((*MockChallengeRepository)(nil).InvalidateOpen), ctx, applicationID, target, challengeType)
}

// MockChallengeService is a mock of IService interface.
type MockChallengeService struct {
	ctrl     *gomock.Controller
	recorder *MockChallengeServiceMockRecorder
	isgomock struct{}
}

// MockChallengeServiceMockRecorder is the mock recorder for MockChallengeService.
type MockChallengeServiceMockRecorder struct {
	mock *MockChallengeService
}

// NewMockChallengeService creates a new mock instance.
func NewMockChallengeService(ctrl *gomock.Controller) *MockChallengeService {
	mock := &MockChallengeService{ctrl: ctrl}
	mock.recorder = &MockChallengeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallengeService) EXPECT() *MockChallengeServiceMockRecorder {
	return m.recorder
}

// ConsumeMagicLink mocks base method.
func (m *MockChallengeService) ConsumeMagicLink(ctx context.Context, applicationID uuid.UUID, token, email string) (challenge.Challenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeMagicLink", ctx, applicationID, token, email)
	ret0, _ := ret[0].(challenge.Challenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeMagicLink indicates an expected call of ConsumeMagicLink.
func (mr *MockChallengeServiceMockRecorder) ConsumeMagicLink(ctx, applicationID, token, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeMagicLink", reflect.TypeOf((*MockChallengeService)(nil).ConsumeMagicLink), ctx, applicationID, token, email)
}

// IssueMagicLink mocks base method.
func (m *MockChallengeService) IssueMagicLink(ctx context.Context, applicationID uuid.UUID, userID *uuid.UUID, email string, ttlSeconds int) (string, time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueMagicLink", ctx, applicationID, userID, email, ttlSeconds)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Duration)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssueMagicLink indicates an expected call of IssueMagicLink.
func (mr *MockChallengeServiceMockRecorder) IssueMagicLink(ctx, applicationID, userID, email, ttlSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueMagicLink", reflect.TypeOf((*MockChallengeService)(nil).IssueMagicLink), ctx, applicationID, userID, email, ttlSeconds)
}

// IssueOTP mocks base method.
func (m *MockChallengeService) IssueOTP(ctx context.Context, applicationID uuid.UUID, userID *uuid.UUID, email string, length, ttlSeconds int) (string, time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueOTP", ctx, applicationID, userID, email, length, ttlSeconds)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Duration)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssueOTP indicates an expected call of IssueOTP.
func (mr *MockChallengeServiceMockRecorder) IssueOTP(ctx, applicationID, userID, email, length, ttlSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueOTP", reflect.TypeOf((*MockChallengeService)(nil).IssueOTP), ctx, applicationID, userID, email, length, ttlSeconds)
}

// VerifyOTP mocks base method.
func (m *MockChallengeService) VerifyOTP(ctx context.Context, applicationID uuid.UUID, email, code string, maxAttempts int) (challenge.Challenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOTP", ctx, applicationID, email, code, maxAttempts)
	ret0, _ := ret[0].(challenge.Challenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyOTP indicates an expected call of VerifyOTP.
func (mr *MockChallengeServiceMockRecorder) VerifyOTP(ctx, applicationID, email, code, maxAttempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOTP", reflect.TypeOf((*MockChallengeService)(nil).VerifyOTP), ctx, applicationID, email, code, maxAttempts)
}
