// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imabg/authx/internal/token (interfaces: IService)
//
// Generated by this command:
//
//	mockgen -destination=mock/token_mock.go -package=mock -mock_names=IService=MockTokenService github.com/imabg/authx/internal/token IService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	app "github.com/imabg/authx/internal/app"
	token "github.com/imabg/authx/internal/token"
	users "github.com/imabg/authx/internal/users"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenService is a mock of IService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MockTokenService) Issue(ctx context.Context, user users.User, application *app.Application) (token.Pair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", ctx, user, application)
	ret0, _ := ret[0].(token.Pair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockTokenServiceMockRecorder) Issue(ctx, user, application any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockTokenService)(nil).Issue), ctx, user, application)
}

// LookupRefresh mocks base method.
func (m *MockTokenService) LookupRefresh(ctx context.Context, refreshToken string) (token.RefreshRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupRefresh", ctx, refreshToken)
	ret0, _ := ret[0].(token.RefreshRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupRefresh indicates an expected call of LookupRefresh.
func (mr *MockTokenServiceMockRecorder) LookupRefresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupRefresh", reflect.TypeOf((*MockTokenService)(nil).LookupRefresh), ctx, refreshToken)
}

// ParseAccess mocks base method.
func (m *MockTokenService) ParseAccess(arg0 string) (*token.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccess", arg0)
	ret0, _ := ret[0].(*token.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccess indicates an expected call of ParseAccess.
func (mr *MockTokenServiceMockRecorder) ParseAccess(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccess", reflect.TypeOf((*MockTokenService)(nil).ParseAccess), arg0)
}

// Revoke mocks base method.
func (m *MockTokenService) Revoke(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockTokenServiceMockRecorder) Revoke(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockTokenService)(nil).Revoke), ctx, refreshToken)
}

// Rotate mocks base method.
func (m *MockTokenService) Rotate(ctx context.Context, refreshToken string, applicationID uuid.UUID, user users.User, application *app.Application) (token.Pair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, refreshToken, applicationID, user, application)
	ret0, _ := ret[0].(token.Pair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rotate indicates an expected call of Rotate.
func (mr *MockTokenServiceMockRecorder) Rotate(ctx, refreshToken, applicationID, user, application any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockTokenService)(nil).Rotate), ctx, refreshToken, applicationID, user, application)
}
